blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/skynetbee/ReactNeuralEngine/discussions
    about: For questions, ideas, and general discussion
  - name: 🆘 Stack Overflow
    url: https://stackoverflow.com/questions/tagged/react
    about: For technical React questions
  - name: 📧 Email Support
    url: mailto:support@reactneuralengine.com
    about: For private support inquiries

